[project]
name = "voice-recorder"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "pillow>=11.3.0",
    "scipy>=1.16.1",
    "sounddevice>=0.5.2",
]
